{%- set alerts = {} %}
{%- set recordings = {} %}

{%- if server.get('use_grains', {}).get('recording', True) %}
  {%- for node_name, node_grains in salt['mine.get']('*', 'grains.items').items() %}
    {%- set server_grain = node_grains.get('prometheus', {}).get('server', {}) %}
    {%- for recordingname, recording in server_grain.get('recording', {}).items() %}
      {%- do recordings.update({recordingname: recording}) %}
    {%- endfor %}
  {%- endfor %}
{%- endif %}

{%- set recordings = salt['grains.filter_by']({'default': recordings}, merge=server.get('recording', {})) %}

{%- for recordingname, recording in recordings.items() %}
  {%- if recording.get('enabled', True) %}
    {{ recordingname }} = {{ recording.query }}
  {%- endif %}
{%- endfor %}

{%- if server.get('use_grains', {}).get('alert', True) %}
  {%- for node_name, node_grains in salt['mine.get']('*', 'grains.items').items() %}
    {%- set server_grain = node_grains.get('prometheus', {}).get('server', {}) %}
    {%- for alertname, alert in server_grain.get('alert', {}).items() %}
      {%- do alerts.update({alertname: alert}) %}
    {%- endfor %}
  {%- endfor %}
{%- endif %}

{%- set alerts = salt['grains.filter_by']({'default': alerts}, merge=server.get('alert', {})) %}

{%- for alertname, alert in alerts.items() %}
  {%- if alert.get('enabled', True) %}
    ALERT {{ alertname }}
      IF {{ alert.if }}
      {%- if alert.for is defined %}
      FOR {{ alert.for }}{%- endif %}
      {#- Handle labels #}
      {%- if alert.labels is not defined %}
        {%- do alert.update({'labels': {}}) %}
      {%- endif %}
      {%- for label_name, label_value in server.get('config', {}).get('alert', {}).get('labels_add', {}).items() %}
        {%- if label_name not in alert.labels %}
          {%- do alert.labels.update({label_name: label_value}) %}
        {%- endif %}
      {%- endfor %}
      {%- if alert.labels %}
      LABELS {
        {%- for name, value in alert.labels.items() %}
        {{ name }} = "{{ value }}"{%- if not loop.last %},{%- endif %}
        {%- endfor %}
      }
      {%- endif %}
      {#- Handle annotations #}
      {%- if alert.annotations is defined %}
      ANNOTATIONS {
        {%- for name, value in alert.annotations.items() %}
        {{ name }} = "{{ value }}"{%- if not loop.last %},{%- endif %}
        {%- endfor %}
      }
      {%- endif %}
  {%- endif %}
{%- endfor %}
